require('dotenv').config();const express=require('express'),http=require('http'),{Server}=require('socket.io'),bcrypt=require('bcryptjs'),crypto=require('crypto'),{pool}=require('./db'),{initialBoard,legalMoves,applyMove,hasPieces}=require('./game');
const app=express(),server=http.createServer(app),io=new Server(server);app.use(express.json());app.use(express.static('public'));
const sessions=new Map(),rooms=new Map();
const code=()=>crypto.randomBytes(3).toString('hex').toUpperCase();
async function userFrom(req){const u=sessions.get(req.headers.authorization?.replace('Bearer ','')||'');return u}
app.post('/api/register',async(req,res)=>{try{const {username,password}=req.body;if(!/^[A-Za-z0-9_]{3,40}$/.test(username)||!password||password.length<6)return res.status(400).json({error:'Username must be 3-40 characters and password at least 6 characters.'});const hash=await bcrypt.hash(password,12);const [r]=await pool.execute('INSERT INTO users(username,password_hash) VALUES(?,?)',[username,hash]);res.json({ok:true,id:r.insertId})}catch(e){res.status(400).json({error:e.code==='ER_DUP_ENTRY'?'Username already exists':'Registration failed'})}});
app.post('/api/login',async(req,res)=>{const {username,password}=req.body;const [rows]=await pool.execute('SELECT * FROM users WHERE username=?',[username]);if(!rows[0]||!(await bcrypt.compare(password,rows[0].password_hash)))return res.status(401).json({error:'Invalid login'});const token=crypto.randomBytes(32).toString('hex');const u={id:rows[0].id,username:rows[0].username,role:rows[0].role};sessions.set(token,u);res.json({token,user:u})});
app.get('/api/me',async(req,res)=>{const u=await userFrom(req);if(!u)return res.status(401).json({error:'Login required'});const [r]=await pool.execute('SELECT id,username,role,wins,losses,draws,streak,best_streak,captures FROM users WHERE id=?',[u.id]);res.json(r[0])});
app.get('/api/leaderboard',async(req,res)=>{const [r]=await pool.execute('SELECT username,wins,losses,draws,streak,best_streak,captures,(wins+losses+draws) games FROM users ORDER BY wins DESC,best_streak DESC LIMIT 50');res.json(r)});
app.get('/api/history',async(req,res)=>{const u=await userFrom(req);if(!u)return res.status(401).json({error:'Login required'});const [r]=await pool.execute(`SELECT g.id,g.room_code,g.status,g.result_reason,g.created_at,g.finished_at,u1.username player1,u2.username player2,w.username winner FROM games g LEFT JOIN users u1 ON u1.id=g.player1_id LEFT JOIN users u2 ON u2.id=g.player2_id LEFT JOIN users w ON w.id=g.winner_id WHERE g.player1_id=? OR g.player2_id=? ORDER BY g.id DESC LIMIT 50`,[u.id,u.id]);res.json(r)});
app.get('/api/admin/users',async(req,res)=>{const u=await userFrom(req);if(!u||u.role!=='admin')return res.status(403).json({error:'Admin only'});const [r]=await pool.execute('SELECT id,username,role,wins,losses,draws,created_at FROM users ORDER BY id DESC');res.json(r)});
function emitRoom(room){io.to(room.code).emit('state',{board:room.board,turn:room.turn,players:room.players,status:room.status,lastMove:room.lastMove,chat:room.chat.slice(-30),winner:room.winner})}
async function finish(room,winner,reason){if(room.status==='finished'||room.status==='draw')return;room.status=winner?'finished':'draw';room.winner=winner||null;await pool.execute('UPDATE games SET status=?,winner_id=?,result_reason=?,finished_at=NOW() WHERE id=?',[room.status,winner?.id||null,reason,room.gameId]);if(winner){const loser=room.players.find(p=>p.id!==winner.id);await pool.execute('UPDATE users SET wins=wins+1,streak=streak+1,best_streak=GREATEST(best_streak,streak+1) WHERE id=?',[winner.id]);if(loser)await pool.execute('UPDATE users SET losses=losses+1,streak=0 WHERE id=?',[loser.id]);}}
io.on('connection',socket=>{socket.on('join',async({token,roomCode,ai=false})=>{const u=sessions.get(token);if(!u)return socket.emit('errorMsg','Please login first.');let room=rooms.get(roomCode);if(!room){room={code:roomCode,board:initialBoard(),turn:'r',players:[{...u,color:'r'}],status:'waiting',chat:[],lastMove:null,winner:null};const [r]=await pool.execute('INSERT INTO games(room_code,player1_id,status) VALUES(?,? ,"waiting")',[roomCode,u.id]);room.gameId=r.insertId;rooms.set(roomCode,room)}else if(!room.players.find(p=>p.id===u.id)&&room.players.length<2){room.players.push({...u,color:'b'});room.status='playing';await pool.execute('UPDATE games SET player2_id=?,status="playing",started_at=NOW() WHERE id=?',[u.id,room.gameId])}socket.join(roomCode);emitRoom(room)});
socket.on('move',async({token,roomCode,from,to})=>{const room=rooms.get(roomCode),u=sessions.get(token);if(!room||!u||room.status!=='playing')return;const pl=room.players.find(p=>p.id===u.id);if(!pl||pl.color!==room.turn)return;const legal=legalMoves(room.board,pl.color),m=legal.find(x=>x.from===from&&x.to===to);if(!m)return socket.emit('errorMsg','Illegal move.');room.board=applyMove(room.board,m);room.lastMove=m;const opponent=pl.color==='r'?'b':'r';const [rr]=await pool.execute('INSERT INTO game_moves(game_id,user_id,move_no,from_sq,to_sq,captures_json) VALUES(?,?,?,?,?,?)',[room.gameId,u.id,(await pool.execute('SELECT COUNT(*) n FROM game_moves WHERE game_id=?',[room.gameId]))[0][0].n,from,to,JSON.stringify(m.captures)]);if(m.captures.length)await pool.execute('UPDATE users SET captures=captures+? WHERE id=?',[m.captures.length,u.id]);if(!hasPieces(room.board,opponent)||legalMoves(room.board,opponent).length===0)await finish(room,pl,'checkmate');else room.turn=opponent;emitRoom(room)});
socket.on('resign',async({token,roomCode})=>{const room=rooms.get(roomCode),u=sessions.get(token);if(!room)return;const winner=room.players.find(p=>p.id!==u?.id);if(winner)await finish(room,winner,'resignation');emitRoom(room)});socket.on('draw',async({token,roomCode})=>{const room=rooms.get(roomCode);if(!room)return;await finish(room,null,'draw agreed');emitRoom(room)});socket.on('chat',({token,roomCode,message})=>{const room=rooms.get(roomCode),u=sessions.get(token);if(!room||!u||!message)return;room.chat.push({username:u.username,message:String(message).slice(0,300),at:Date.now()});emitRoom(room)});});
app.get('*',(req,res)=>res.sendFile(require('path').join(process.cwd(),'public','index.html')));server.listen(process.env.PORT||3000,()=>console.log('Dama server running on port '+(process.env.PORT||3000)));
